defmodule SentinelCp.Services.KdlGenerator do
  @moduledoc """
  Generates KDL configuration from structured service definitions.

  Pure function module — reads services and project config, produces KDL text.
  """

  alias SentinelCp.Services
  alias SentinelCp.Services.{Service, ProjectConfig}

  @doc """
  Generates KDL configuration for a project from its services and config.

  Returns `{:ok, kdl_string}` or `{:error, :no_services}`.
  """
  def generate(project_id) do
    services = Services.list_services(project_id, enabled: true)

    if services == [] do
      {:error, :no_services}
    else
      {:ok, config} = Services.get_or_create_project_config(project_id)
      kdl = build_kdl(services, config)
      {:ok, kdl}
    end
  end

  @doc """
  Generates KDL from provided services and config (no DB access).
  Useful for testing.
  """
  def build_kdl(services, %ProjectConfig{} = config) do
    parts = [
      "// Generated by Sentinel Control Plane",
      "// Do not edit manually — managed via Services UI",
      "",
      build_settings(config),
      "",
      build_routes(services),
      build_rate_limits(services)
    ]

    parts
    |> List.flatten()
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  defp build_settings(%ProjectConfig{} = config) do
    lines = [
      "settings {",
      "    log_level #{inspect(config.log_level)}",
      "    metrics_port #{config.metrics_port}"
    ]

    custom_lines =
      (config.custom_settings || %{})
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "    #{key} #{format_value(value)}" end)

    lines ++ custom_lines ++ ["}"]
  end

  defp build_routes(services) do
    route_blocks =
      services
      |> Enum.map(&build_route/1)
      |> Enum.intersperse([""])

    ["routes {"] ++ List.flatten(route_blocks) ++ ["}"]
  end

  defp build_route(%Service{} = service) do
    lines = ["    route #{inspect(service.route_path)} {"]

    lines =
      if service.upstream_url do
        lines ++ ["        upstream #{inspect(service.upstream_url)}"]
      else
        lines ++
          ["        respond #{service.respond_status} #{inspect(service.respond_body || "")}"]
      end

    lines =
      if service.timeout_seconds do
        lines ++ ["        timeout #{service.timeout_seconds}s"]
      else
        lines
      end

    lines = lines ++ build_retry_block(service.retry)
    lines = lines ++ build_cache_block(service.cache)
    lines = lines ++ build_health_check_block(service.health_check)
    lines = lines ++ build_headers_block(service.headers)

    lines ++ ["    }"]
  end

  defp build_retry_block(retry) when retry == %{} or retry == nil, do: []

  defp build_retry_block(retry) do
    inner =
      retry
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "            #{key} #{format_value(value)}" end)

    if inner == [] do
      []
    else
      ["        retry {"] ++ inner ++ ["        }"]
    end
  end

  defp build_cache_block(cache) when cache == %{} or cache == nil, do: []

  defp build_cache_block(cache) do
    inner =
      cache
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "            #{key} #{format_value(value)}" end)

    if inner == [] do
      []
    else
      ["        cache {"] ++ inner ++ ["        }"]
    end
  end

  defp build_health_check_block(hc) when hc == %{} or hc == nil, do: []

  defp build_health_check_block(hc) do
    inner =
      hc
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "            #{key} #{format_value(value)}" end)

    if inner == [] do
      []
    else
      ["        health_check {"] ++ inner ++ ["        }"]
    end
  end

  defp build_headers_block(headers) when headers == %{} or headers == nil, do: []

  defp build_headers_block(headers) do
    inner =
      headers
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "            #{key} #{format_value(value)}" end)

    if inner == [] do
      []
    else
      ["        headers {"] ++ inner ++ ["        }"]
    end
  end

  defp build_rate_limits(services) do
    rate_limited =
      services
      |> Enum.filter(fn s -> s.rate_limit && s.rate_limit != %{} end)

    if rate_limited == [] do
      []
    else
      blocks =
        rate_limited
        |> Enum.map(&build_rate_limit_entry/1)
        |> Enum.intersperse([""])

      ["", "rate_limits {"] ++ List.flatten(blocks) ++ ["}"]
    end
  end

  defp build_rate_limit_entry(%Service{} = service) do
    inner =
      service.rate_limit
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "        #{key} #{format_value(value)}" end)

    ["    limit #{inspect(service.slug)} {"] ++ inner ++ ["    }"]
  end

  defp format_value(value) when is_binary(value), do: inspect(value)
  defp format_value(value) when is_integer(value), do: Integer.to_string(value)
  defp format_value(value) when is_float(value), do: Float.to_string(value)
  defp format_value(true), do: "true"
  defp format_value(false), do: "false"
  defp format_value(value), do: inspect(value)
end
